#!/usr/bin/env bash
# A bash script that debugs  nginx port 80.
# Requirements: Nginx must be running, and listening on port 80 of all the server’s active IPv4 IPs
# Steps: delete the existing ../sites-enabled/default and replace it with a copy of
# ../sites-available/default. You do that by creating a symbolic link using flag -s and
# flage -f to delete the existing file and replaces it

sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
