#!/usr/bin/env bash
# A script that prints "to infinity and beyond" indefinitely.
# Requirements:
#	sleep 2 in between iterations.
#	displays "I am invincible!!!" when receiving a SIGTERM signal

trap 'echo "I am invincible!!!"' SIGTERM

while true
do
	echo "To infinity and beyond"
	sleep 2
done
