#!/usr/bin/env bash
# A script that displays no from 1-20 with replacement at certain positions.
i=1
while ((1 < 21))
do
	echo $i
	case "$i" in
		4) echo "bad luck from China";;
		9) echo "bad luck from Japan";;
		17) echo "bad luch from Italy";;
		esac
	((i++))
done
